version: "3.7"
services:
  
  nginx:
    image: nginx:alpine
    container_name: prueba-spira-nginx
    restart: unless-stopped    
    ports:
        - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - prueba-spira

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor 
    networks:
      - prueba-spira

  db:
    image: mysql:5.7
    container_name: prueba-spira-db
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: prueba-spira
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_PASSWORD: prueba-spira
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db/config/my.conf:/etc/mysql/conf.d/config-file.cnf
      - ./db/mysql:/var/lib/mysql:rw
    networks:
      - prueba-spira

  app:
    build:
      args:
        user: userprueba-spira
        uid: 1000
      context: ./app
      dockerfile: Dockerfile
    image: prueba-spira
    container_name: prueba-spira-app-laravel
    restart: unless-stopped
    working_dir:  /var/www/    
    ports: 
      - "9000:9000"
    volumes:
      - ../src:/var/www
    networks:
      - prueba-spira

networks:
    prueba-spira:
        driver: bridge
